name: uper-build

on:
    push:
        paths:
            - ".github/workflows/upper-build.yaml"
            - "upper/**"
    workflow_dispatch: # manual

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: upper 
        steps:
            - run: pwd && ls -al
            - uses: actions/checkout@v4
            - run: pwd && ls -al
            - run: go version
            - uses: actions/setup-go@v5
              with:
                go-version: '1.22'
                cache: true
                cache-dependency-path: upper/go.sum
            # - run: go mod init
            - run: go version
            - run: go build
            - run: |
                ls
                go build
                ls
                go test
                ./upper foo the bar
              working-directory: upper
